# Generated by Django 6.0.4 on 2026-04-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='category_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='hourly_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
